"""helix_agent.api — Multi-provider LLM client."""

from .base import BaseClient
from .anthropic import AnthropicClient, AuthSource, MessageStream, OAuthTokenSet
from .openai_compat import OpenAICompatClient
from .factory import Provider, create_client
from .error import (
    ApiError,
    ApiResponseError,
    AuthError,
    BackoffOverflow,
    ExpiredOAuthToken,
    HttpError,
    InvalidApiKeyEnv,
    InvalidSseFrame,
    IoError,
    JsonError,
    MissingApiKey,
    RetriesExhausted,
    is_retryable_status,
)
from .sse import SseParser, parse_frame
from .types import (
    ContentBlockDelta,
    ContentBlockDeltaEvent,
    ContentBlockStartEvent,
    ContentBlockStopEvent,
    InputContentBlock,
    InputJsonDelta,
    InputMessage,
    MessageDelta,
    MessageDeltaEvent,
    MessageRequest,
    MessageResponse,
    MessageStartEvent,
    MessageStopEvent,
    OutputContentBlock,
    StreamEvent,
    TextDelta,
    TextInputBlock,
    TextOutputBlock,
    TextToolResult,
    ToolChoice,
    ToolChoiceAny,
    ToolChoiceAuto,
    ToolChoiceTool,
    ToolDefinition,
    ToolResultInputBlock,
    ToolUseInputBlock,
    ToolUseOutputBlock,
    Usage,
    parse_stream_event,
)

__all__ = [
    # factory
    "create_client",
    "Provider",
    # clients
    "BaseClient",
    "AnthropicClient",
    "OpenAICompatClient",
    # anthropic extras
    "AuthSource",
    "MessageStream",
    "OAuthTokenSet",
    # errors
    "ApiError",
    "ApiResponseError",
    "AuthError",
    "BackoffOverflow",
    "ExpiredOAuthToken",
    "HttpError",
    "InvalidApiKeyEnv",
    "InvalidSseFrame",
    "IoError",
    "JsonError",
    "MissingApiKey",
    "RetriesExhausted",
    "is_retryable_status",
    # sse
    "SseParser",
    "parse_frame",
    # types
    "ContentBlockDelta",
    "ContentBlockDeltaEvent",
    "ContentBlockStartEvent",
    "ContentBlockStopEvent",
    "InputContentBlock",
    "InputJsonDelta",
    "InputMessage",
    "MessageDelta",
    "MessageDeltaEvent",
    "MessageRequest",
    "MessageResponse",
    "MessageStartEvent",
    "MessageStopEvent",
    "OutputContentBlock",
    "StreamEvent",
    "TextDelta",
    "TextInputBlock",
    "TextOutputBlock",
    "TextToolResult",
    "ToolChoice",
    "ToolChoiceAny",
    "ToolChoiceAuto",
    "ToolChoiceTool",
    "ToolDefinition",
    "ToolResultInputBlock",
    "ToolUseInputBlock",
    "ToolUseOutputBlock",
    "Usage",
    "parse_stream_event",
]
